title: theZoo aka Malware DB
description: A repository of LIVE malwares for your own joy and pleasure
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-53267734-2

gems:
  - jekyll-mentions
